/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Customer;

import Enterprise.main.EcoSystem;
import Enterprise.Customer.Customer;

/**
 *
 * @author vardhankaranam25
 */
public class CustomerHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerHome
     */
    
    EcoSystem system;
    Customer user;
    
    public CustomerHomePanel(EcoSystem system, Customer user) {
        initComponents();
        this.system = system;
        this.user = user;
        
        jLabel3.setText(user.getFirstName() + " " + user.getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userLeftPanel = new javax.swing.JPanel();
        bookVehicleBtn = new javax.swing.JButton();
        bookSwimmingPoolBtn = new javax.swing.JButton();
        bookGameRoomBtn = new javax.swing.JButton();
        bookLaundryBtn = new javax.swing.JButton();
        GiftwareBtn = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        bookDining = new javax.swing.JButton();
        userRightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        userLeftPanel.setBackground(new java.awt.Color(102, 102, 255));

        bookVehicleBtn.setBackground(new java.awt.Color(255, 204, 204));
        bookVehicleBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookVehicleBtn.setForeground(new java.awt.Color(102, 102, 255));
        bookVehicleBtn.setText("Book Vehicle");
        bookVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookVehicleBtnActionPerformed(evt);
            }
        });

        bookSwimmingPoolBtn.setBackground(new java.awt.Color(255, 204, 204));
        bookSwimmingPoolBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookSwimmingPoolBtn.setForeground(new java.awt.Color(102, 102, 255));
        bookSwimmingPoolBtn.setText("Book Pool");
        bookSwimmingPoolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSwimmingPoolBtnActionPerformed(evt);
            }
        });

        bookGameRoomBtn.setBackground(new java.awt.Color(255, 204, 204));
        bookGameRoomBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookGameRoomBtn.setForeground(new java.awt.Color(102, 102, 255));
        bookGameRoomBtn.setText("Book Games");
        bookGameRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookGameRoomBtnActionPerformed(evt);
            }
        });

        bookLaundryBtn.setBackground(new java.awt.Color(255, 204, 204));
        bookLaundryBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookLaundryBtn.setForeground(new java.awt.Color(102, 102, 255));
        bookLaundryBtn.setText("Laundry");
        bookLaundryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookLaundryBtnActionPerformed(evt);
            }
        });

        GiftwareBtn.setBackground(new java.awt.Color(255, 204, 204));
        GiftwareBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GiftwareBtn.setForeground(new java.awt.Color(102, 102, 255));
        GiftwareBtn.setText("Giftware Shop");
        GiftwareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiftwareBtnActionPerformed(evt);
            }
        });

        checkOutBtn.setBackground(new java.awt.Color(255, 204, 204));
        checkOutBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        checkOutBtn.setForeground(new java.awt.Color(102, 102, 255));
        checkOutBtn.setText("Checkout");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        bookDining.setBackground(new java.awt.Color(255, 204, 204));
        bookDining.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookDining.setForeground(new java.awt.Color(102, 102, 255));
        bookDining.setText("Food and Beverage");
        bookDining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDiningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLeftPanelLayout = new javax.swing.GroupLayout(userLeftPanel);
        userLeftPanel.setLayout(userLeftPanelLayout);
        userLeftPanelLayout.setHorizontalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bookDining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookVehicleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookSwimmingPoolBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookGameRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookLaundryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GiftwareBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userLeftPanelLayout.setVerticalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(bookVehicleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookSwimmingPoolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookGameRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookDining, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookLaundryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GiftwareBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(userLeftPanel);

        userRightPanel.setBackground(new java.awt.Color(255, 204, 204));
        userRightPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Customer Home Panel");
        userRightPanel.add(jLabel1);
        jLabel1.setBounds(570, 30, 430, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Welcome to the Best Place in the World");
        userRightPanel.add(jLabel2);
        jLabel2.setBounds(650, 90, 340, 21);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userRightPanel.add(jLabel3);
        jLabel3.setBounds(550, 190, 240, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palm.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        userRightPanel.add(jLabel5);
        jLabel5.setBounds(0, -70, 1290, 1220);

        jSplitPane1.setRightComponent(userRightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GiftwareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiftwareBtnActionPerformed
        // Redirect User to Shopping Panel
        ShopPanel bookShop = new ShopPanel(system, user);
        jSplitPane1.setRightComponent(bookShop);
    }//GEN-LAST:event_GiftwareBtnActionPerformed

    private void bookVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookVehicleBtnActionPerformed
        // Redirect User to Vehicle Booking Panel
        VehicleBookingPanel bookVehicle = new VehicleBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookVehicle);
    }//GEN-LAST:event_bookVehicleBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
        CheckoutPanel checkout = new CheckoutPanel(system, user);
        jSplitPane1.setRightComponent(checkout);
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void bookDiningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookDiningActionPerformed
        // TODO add your handling code here:
        FoodBookingPanel bookFood = new FoodBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookFood);
    }//GEN-LAST:event_bookDiningActionPerformed

    private void bookSwimmingPoolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSwimmingPoolBtnActionPerformed
        // TODO add your handling code here:
        PoolBookingPanel bookPool = new PoolBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookPool);
    }//GEN-LAST:event_bookSwimmingPoolBtnActionPerformed

    private void bookGameRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookGameRoomBtnActionPerformed
        // TODO add your handling code here:
        GameBookingPanel bookGame = new GameBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookGame);
    }//GEN-LAST:event_bookGameRoomBtnActionPerformed

    private void bookLaundryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookLaundryBtnActionPerformed
        // TODO add your handling code here:
        LaundryPanel bookLaundry = new LaundryPanel(system, user);
        jSplitPane1.setRightComponent(bookLaundry);
    }//GEN-LAST:event_bookLaundryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GiftwareBtn;
    private javax.swing.JButton bookDining;
    private javax.swing.JButton bookGameRoomBtn;
    private javax.swing.JButton bookLaundryBtn;
    private javax.swing.JButton bookSwimmingPoolBtn;
    private javax.swing.JButton bookVehicleBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userLeftPanel;
    private javax.swing.JPanel userRightPanel;
    // End of variables declaration//GEN-END:variables
}
