/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Customer;

import Enterprise.main.EcoSystem;
import Enterprise.RecreationEvents.SwimmingPool.SwimmingPool;
import Enterprise.Customer.Customer;
import Enterprise.ServiceRequest.SwimmingPoolServiceRequest;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.MutableComboBoxModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vardhankaranam25
 */
public class PoolBookingPanel extends javax.swing.JPanel {

    /**
     * Creates new form PoolBookingPanel
     */
    EcoSystem system;
    Customer user;

    public PoolBookingPanel(EcoSystem system, Customer user) {
        initComponents();

        this.system = system;
        this.user = user;

        MutableComboBoxModel<String> model = new DefaultComboBoxModel<String>();

        for (SwimmingPool poolList : system.getSwimmingPoolList().getPoolDirectory()) {
            model.addElement(poolList.getSwimmingpoolName());
        }

        choosePoolDropdown.setModel(model);

        poolNameTxt.setEditable(false);
        priceTxt.setEditable(false);

        populateRequestTable();
        formatRows();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPoolBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numberOfHoursTxt = new javax.swing.JTextField();
        poolBookingDateTxt = new com.toedter.calendar.JDateChooser();
        bookPoolBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        poolWorkQueueTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        choosePoolDropdown = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        poolNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 222, 242));
        setForeground(new java.awt.Color(157, 193, 131));
        setLayout(null);

        viewPoolBtn.setBackground(new java.awt.Color(255, 222, 242));
        viewPoolBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewPoolBtn.setText("View Details");
        viewPoolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPoolBtnActionPerformed(evt);
            }
        });
        add(viewPoolBtn);
        viewPoolBtn.setBounds(720, 280, 105, 23);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price per hour:");
        add(jLabel6);
        jLabel6.setBounds(580, 360, 100, 20);
        add(priceTxt);
        priceTxt.setBounds(700, 360, 160, 23);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Select Pool Booking Date:");
        add(jLabel7);
        jLabel7.setBounds(80, 460, 157, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter Number of Hours:");
        add(jLabel8);
        jLabel8.setBounds(480, 450, 150, 17);
        add(numberOfHoursTxt);
        numberOfHoursTxt.setBounds(650, 450, 160, 23);

        poolBookingDateTxt.setDateFormatString("MM/dd/yyyy");
        add(poolBookingDateTxt);
        poolBookingDateTxt.setBounds(270, 450, 160, 23);

        bookPoolBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bookPoolBtn.setText("Book Pool");
        bookPoolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPoolBtnActionPerformed(evt);
            }
        });
        add(bookPoolBtn);
        bookPoolBtn.setBounds(870, 430, 137, 50);

        poolWorkQueueTable.setForeground(new java.awt.Color(157, 193, 131));
        poolWorkQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pool Name", "Booking Date", "Price per hour", "Number of hours", "Total Price", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(poolWorkQueueTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(80, 570, 933, 257);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book A Swimming Pool");
        add(jLabel1);
        jLabel1.setBounds(330, 210, 390, 40);

        add(choosePoolDropdown);
        choosePoolDropdown.setBounds(530, 280, 148, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose a pool of your choice:");
        add(jLabel2);
        jLabel2.setBounds(290, 290, 178, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pool Booking Status");
        add(jLabel9);
        jLabel9.setBounds(410, 520, 180, 21);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pool Name:");
        add(jLabel3);
        jLabel3.setBounds(230, 360, 71, 17);
        add(poolNameTxt);
        poolNameTxt.setBounds(330, 360, 160, 23);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SwimmingPoolImg.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(-20, -10, 1520, 940);
    }// </editor-fold>//GEN-END:initComponents

    private void viewPoolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPoolBtnActionPerformed
        // View Vehicle Details on choosing

        try {
            if (choosePoolDropdown.getSelectedItem() != null) {

                String poolName = String.valueOf(choosePoolDropdown.getSelectedItem());
                SwimmingPool poolDetails = system.getSwimmingPoolList().getPoolByName(poolName);

                poolNameTxt.setText(poolDetails.getSwimmingpoolName());
                priceTxt.setText(String.valueOf(poolDetails.getPrice()));

            } else {
                JOptionPane.showMessageDialog(this, "Choose a valid Pool for booking");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Choose a valid Pool for booking");
        }
    }//GEN-LAST:event_viewPoolBtnActionPerformed

    private void bookPoolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPoolBtnActionPerformed
        // Book a vehicle after entering details
        SwimmingPoolServiceRequest bookPool = new SwimmingPoolServiceRequest();

        try {
            if (choosePoolDropdown.getSelectedItem() != null) {
                String poolName = String.valueOf(choosePoolDropdown.getSelectedItem());
                SwimmingPool poolDetails = system.getSwimmingPoolList().getPoolByName(poolName);

                Date selectedDate = poolBookingDateTxt.getDate();
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                String strDate = dateFormat.format(selectedDate);
                Date bookingDate = dateFormat.parse(strDate);

                int numberOfHours = Integer.parseInt(numberOfHoursTxt.getText());
                String customerId = user.getCustomerId();
                System.out.println(customerId);
                bookPool.setPoolDetails(poolDetails);
                bookPool.setBookingDate(bookingDate);
                bookPool.setNumberOfHours(numberOfHours);
                bookPool.setCustomerId(customerId);
                
                System.out.println(bookPool.getCustomerId());
                bookPool.setStatus("Pending");

                system.getSwimmingPoolServiceRequestList().getSwimmingPoolServiceRequestList().add(bookPool);

                JOptionPane.showMessageDialog(this, "Pool booking request sent to Manager");
                populateRequestTable();
                clearFields();
                formatRows();
                
            } else {
                JOptionPane.showMessageDialog(this, "Enter valid date and number of hours for booking a Pool");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter valid date and number of hours for booking a Pool");
        }
    }//GEN-LAST:event_bookPoolBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookPoolBtn;
    private javax.swing.JComboBox<String> choosePoolDropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numberOfHoursTxt;
    private com.toedter.calendar.JDateChooser poolBookingDateTxt;
    private javax.swing.JTextField poolNameTxt;
    private javax.swing.JTable poolWorkQueueTable;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton viewPoolBtn;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {

        try {
            DefaultTableModel model = (DefaultTableModel) poolWorkQueueTable.getModel();
            model.setRowCount(0);
         
            for (SwimmingPoolServiceRequest poolWorkRequest : system.getSwimmingPoolServiceRequestList().getSwimmingPoolServiceRequestList()) {
// System.out.println(user.getCustomerId());
// System.out.println("h");
// System.out.println(poolWorkRequest.getCustomerId());
                if (poolWorkRequest.getCustomerId().equals(user.getCustomerId())) {
                   
                    Object[] newRow = new Object[6];
                    newRow[0] = poolWorkRequest.getSwimmingPoolDetails().getSwimmingpoolName();
                    newRow[1] = poolWorkRequest.getBookingDate();
                    newRow[2] = poolWorkRequest.getSwimmingPoolDetails().getPrice();
                    newRow[3] = poolWorkRequest.getNumberOfHours();
                    newRow[4] = (poolWorkRequest.getSwimmingPoolDetails().getPrice()*poolWorkRequest.getNumberOfHours());
                    newRow[5] = poolWorkRequest.getStatus();

                    model.addRow(newRow);
                }
            }
        } catch (Exception e) {
           
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void clearFields() {
        
        poolNameTxt.setText("");
        priceTxt.setText("");
        numberOfHoursTxt.setText("");
        poolBookingDateTxt.setCalendar(null);
    }
    
    private void formatRows() {

        DefaultTableModel model = (DefaultTableModel) poolWorkQueueTable.getModel();

        poolWorkQueueTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = String.valueOf(model.getValueAt(row, 5));
                c.setBackground(status.equals("Pending") ? Color.WHITE : status.equals("Approved") ? Color.GREEN : Color.RED);
                return c;
            }
        });

    }
}
