/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.BookaRide;

import Enterprise.main.EcoSystem;
import javax.swing.JOptionPane;

/**
 *
 * @author vardhankaranam25
 */
public class BookVehiclePanel extends javax.swing.JPanel {
    private EcoSystem system;

    /**
     * Creates new form BookVehicle
     */
    public BookVehiclePanel(EcoSystem system) {
        initComponents();
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonPanel = new javax.swing.JPanel();
        btnManageVehicle = new javax.swing.JButton();
        btnRequestQueue = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        imageAreaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        buttonPanel.setBackground(new java.awt.Color(153, 153, 153));

        btnManageVehicle.setBackground(new java.awt.Color(204, 204, 204));
        btnManageVehicle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManageVehicle.setForeground(new java.awt.Color(51, 51, 51));
        btnManageVehicle.setText("MANAGE FLEET");
        btnManageVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehicleActionPerformed(evt);
            }
        });

        btnRequestQueue.setBackground(new java.awt.Color(204, 204, 204));
        btnRequestQueue.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRequestQueue.setForeground(new java.awt.Color(51, 51, 51));
        btnRequestQueue.setText("MANAGE REQUESTS");
        btnRequestQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestQueueActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(51, 51, 51));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRequestQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(btnManageVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRequestQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHome)
                .addContainerGap(533, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(buttonPanel);

        imageAreaPanel.setBackground(new java.awt.Color(242, 233, 174));
        imageAreaPanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lambocar.jpeg"))); // NOI18N
        imageAreaPanel.add(jLabel2);
        jLabel2.setBounds(-380, 0, 1710, 920);

        jSplitPane1.setRightComponent(imageAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehicleActionPerformed
        // TODO add your handling code here:
        
            ManageVehiclePanel managevehiclePanel = new ManageVehiclePanel(system);
            jSplitPane1.setRightComponent(managevehiclePanel);
       
    }//GEN-LAST:event_btnManageVehicleActionPerformed

    private void btnRequestQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestQueueActionPerformed
        // TODO add your handling code here:
       
            ManageVehicleRequestsPanel manageRequestsPanel = new ManageVehicleRequestsPanel(system);
            jSplitPane1.setRightComponent(manageRequestsPanel);
        
        
    }//GEN-LAST:event_btnRequestQueueActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        try {
            HomeVehiclePanel homeVehiclePanel = new HomeVehiclePanel();
            jSplitPane1.setRightComponent(homeVehiclePanel);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnManageVehicle;
    private javax.swing.JButton btnRequestQueue;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imageAreaPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
