/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.GameRoom;

import Enterprise.main.EcoSystem;
import Enterprise.EmailAddress.EmailAlert;
import Enterprise.Payments.CustomerPayments;
import Enterprise.Customer.Customer;
import Enterprise.ServiceRequest.GameRoomServiceRequest;
import Enterprise.ServiceRequest.VehicleServiceRequest;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rishika
 */
public class ManageGameRequestsPanel extends javax.swing.JPanel {
     EcoSystem system;

    /**
     * Creates new form ManageGameRequestsPanel
     */
    public ManageGameRequestsPanel(EcoSystem system) {
        initComponents();
        
        this.system = system;
        populateGameRequestTable();
        formatRows();
        
    }
    
    public void populateGameRequestTable() {
        ArrayList<GameRoomServiceRequest> pendingGameRequest = new ArrayList<GameRoomServiceRequest>();
        ArrayList<GameRoomServiceRequest> non_pendingGameRequest = new ArrayList<GameRoomServiceRequest>();

        for (GameRoomServiceRequest gameWRequest : system.getGameRoomServiceRequestList().getGameWorkRequestList()) {
            if (gameWRequest.getStatus().equals("Pending")) {
                pendingGameRequest.add(gameWRequest);
            } else {
                non_pendingGameRequest.add(gameWRequest);
            }
        }

        populate_based_on_status(pendingGameRequest, non_pendingGameRequest);
    }

    public void populate_based_on_status(ArrayList<GameRoomServiceRequest> pendingGameRequest, ArrayList<GameRoomServiceRequest> non_pendingGameRequest) {
        DefaultTableModel model = (DefaultTableModel) tblGameRequests.getModel();
        model.setRowCount(0);
        for (GameRoomServiceRequest gameWRequest : pendingGameRequest) {

            Object[] newRow = new Object[7];
            newRow[0] = gameWRequest;
            newRow[1] = gameWRequest.getGameDetails().getGameName();
            newRow[2] = gameWRequest.getGameDetails().getGameCategory();
            newRow[3] = gameWRequest.getGameDetails().getGameprice();
            newRow[4] = gameWRequest.getNumberOfHours();
            newRow[5] = gameWRequest.getBookingDate();
            newRow[6] = gameWRequest.getStatus();

            model.addRow(newRow);
        }

        DefaultTableModel modelNon_Pending = (DefaultTableModel) tblGameConfirmed.getModel();
        modelNon_Pending.setRowCount(0);
        for (GameRoomServiceRequest gameWRequest : non_pendingGameRequest) {

            Object[] newRow = new Object[7];
            newRow[0] = gameWRequest;
            newRow[1] = gameWRequest.getGameDetails().getGameName();
            newRow[2] = gameWRequest.getGameDetails().getGameCategory();
            newRow[3] = gameWRequest.getGameDetails().getGameprice();
            newRow[4] = gameWRequest.getNumberOfHours();
            newRow[5] = gameWRequest.getBookingDate();
            newRow[6] = gameWRequest.getStatus();

            modelNon_Pending.addRow(newRow);
        }

    }
    
    public void updateWorkRequestStatus(GameRoomServiceRequest selectedGame, String status) {
        selectedGame.setStatus(status);
        int index = 0;
        for (GameRoomServiceRequest gameWRequest : system.getGameRoomServiceRequestList().getGameWorkRequestList()) {
            if (gameWRequest.getCustomerId().equals(selectedGame.getCustomerId())) {
                system.getGameRoomServiceRequestList().updateGameWorkRequest(gameWRequest, index);
                break;
            }
            index++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGameRequests = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGameConfirmed = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 222, 242));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 82, 255));
        jLabel1.setText("Manage Requests");

        tblGameRequests.setBackground(new java.awt.Color(255, 222, 242));
        tblGameRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Game Name", "Category", "Price per hour($)", "No. of Hours", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGameRequests);

        tblGameConfirmed.setBackground(new java.awt.Color(255, 222, 242));
        tblGameConfirmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Game Name", "Category", "Price per hour($)", "No. of Hours", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblGameConfirmed);

        btnApprove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(140, 82, 255));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReject.setForeground(new java.awt.Color(140, 82, 255));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(277, 277, 277))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
         try {
            int selectedRowIndex = tblGameRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to approve.");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) tblGameRequests.getModel();
            GameRoomServiceRequest selectedGameWorkRequest = (GameRoomServiceRequest) model.getValueAt(selectedRowIndex, 0);
            updateWorkRequestStatus(selectedGameWorkRequest, "Approved");
            CustomerPayments ct = new CustomerPayments();
            
            //User definition for email notif
            Customer getUser = system.getCustomerList().getCustomerById(selectedGameWorkRequest.getCustomerId());

            float gamebooking_finalprice = selectedGameWorkRequest.getNumberOfHours() * selectedGameWorkRequest.getGameDetails().getGameprice();
            ct.setCustomerId(selectedGameWorkRequest.getCustomerId());
            ct.setFacilityUsed("Game Booked - " + selectedGameWorkRequest.getGameDetails().getGameName() + " for " + selectedGameWorkRequest.getNumberOfHours() + " hours");
            ct.setCheckoutprice(gamebooking_finalprice);
            system.getCustomerPaymentsList().addCustomerPayment(ct);
            
             //email notification
            new EmailAlert().sendEmail(getUser, "Game",true);
            
            JOptionPane.showMessageDialog(this, "Request approved successfully and email notification sent");
            populateGameRequestTable();
            formatRows();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
         try {
            int selectedRowIndex = tblGameRequests.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to approve.");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) tblGameRequests.getModel();
            GameRoomServiceRequest selectedGameWorkRequest = (GameRoomServiceRequest) model.getValueAt(selectedRowIndex, 0);
            updateWorkRequestStatus(selectedGameWorkRequest, "Rejected");
            CustomerPayments ct = new CustomerPayments();
            Customer getUser = system.getCustomerList().getCustomerById(selectedGameWorkRequest.getCustomerId());

            float gamebooking_finalprice = selectedGameWorkRequest.getNumberOfHours() * selectedGameWorkRequest.getGameDetails().getGameprice();
            ct.setCustomerId(selectedGameWorkRequest.getCustomerId());
            ct.setFacilityUsed("Game Booked - " + selectedGameWorkRequest.getGameDetails().getGameName() + " for " + selectedGameWorkRequest.getNumberOfHours() + " hours");
            ct.setCheckoutprice(gamebooking_finalprice);
            system.getCustomerPaymentsList().addCustomerPayment(ct);
            
             //email notification
            new EmailAlert().sendEmail(getUser, "Game",false);
            JOptionPane.showMessageDialog(this, "Request rejected successfully");
            populateGameRequestTable();
            formatRows();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGameConfirmed;
    private javax.swing.JTable tblGameRequests;
    // End of variables declaration//GEN-END:variables

    private void formatRows() {

        DefaultTableModel model = (DefaultTableModel) tblGameConfirmed.getModel();

        tblGameConfirmed.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = String.valueOf(model.getValueAt(row, 6));
                c.setBackground(status.equals("Pending") ? Color.WHITE : status.equals("Approved") ? Color.GREEN : Color.RED);
                return c;
            }
        });

    }
}
