/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CaretakerShift;

import Enterprise.main.EcoSystem;
import Enterprise.Maintenance.RoomSanitizing.CaretakerShift;
import Enterprise.Customer.Customer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vardhankaranam25
 */
public class CareTakerPanel extends javax.swing.JPanel {

    /**
     * Creates new form JanitorPanel
     */
    EcoSystem system;
    Customer user;

    public CareTakerPanel(EcoSystem system, Customer user) {
        initComponents();
        this.system = system;
        this.user = user;

        populateTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingTasksTable = new javax.swing.JTable();
        acceptTaskBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tasksProgressTables = new javax.swing.JTable();
        completeTaskBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 222, 242));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 82, 255));
        jLabel1.setText("CareTaker Schedule");

        pendingTasksTable.setBackground(new java.awt.Color(255, 222, 242));
        pendingTasksTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pendingTasksTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pendingTasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Room Number", "Cleaning Date", "Cleaning Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pendingTasksTable);

        acceptTaskBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        acceptTaskBtn.setForeground(new java.awt.Color(140, 82, 255));
        acceptTaskBtn.setText("Accept Task");
        acceptTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptTaskBtnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(140, 82, 255));
        jLabel2.setText("Pending Tasks");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(140, 82, 255));
        jLabel3.setText("Tasks In Progress");

        tasksProgressTables.setBackground(new java.awt.Color(255, 222, 242));
        tasksProgressTables.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tasksProgressTables.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tasksProgressTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Room Number", "Cleaning Date", "Cleaning Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tasksProgressTables);

        completeTaskBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        completeTaskBtn.setForeground(new java.awt.Color(140, 82, 255));
        completeTaskBtn.setText("Complete Task");
        completeTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeTaskBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(acceptTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))))
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(completeTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(488, 488, 488))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acceptTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(completeTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptTaskBtnActionPerformed
        // TODO add your handling code here:

        try {
            int index = pendingTasksTable.getSelectedRow();

            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Please select a Task to be assigned to you");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) pendingTasksTable.getModel();
            String scheduleId = String.valueOf(model.getValueAt(index, 0));
            CaretakerShift selectedSchedule = system.getCaretakerShiftList().getScheduleById(scheduleId);

            selectedSchedule.setCustomer(user);
            selectedSchedule.setStatus("In Progress");

            system.getCaretakerShiftList().updateSchedule(selectedSchedule);

            JOptionPane.showMessageDialog(this, "Task assigned to you successfully");
            populateTables();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a Task to be assigned to you");
        }
    }//GEN-LAST:event_acceptTaskBtnActionPerformed

    private void completeTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeTaskBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            int index = tasksProgressTables.getSelectedRow();

            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Please select a Task to be completed");
                return;
            }
            
            DefaultTableModel model = (DefaultTableModel) tasksProgressTables.getModel();
            String scheduleId = String.valueOf(model.getValueAt(index, 0));
            CaretakerShift selectedSchedule = system.getCaretakerShiftList().getScheduleById(scheduleId);
            
            selectedSchedule.setStatus("Completed");

            system.getCaretakerShiftList().updateSchedule(selectedSchedule);

            JOptionPane.showMessageDialog(this, "Task completed successfully");
            populateTables();
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a Task to be completed");
        }
    }//GEN-LAST:event_completeTaskBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptTaskBtn;
    private javax.swing.JButton completeTaskBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pendingTasksTable;
    private javax.swing.JTable tasksProgressTables;
    // End of variables declaration//GEN-END:variables

    private void populateTables() {

        try {

            DefaultTableModel pendingModel = (DefaultTableModel) pendingTasksTable.getModel();
            DefaultTableModel progressModel = (DefaultTableModel) tasksProgressTables.getModel();
            pendingModel.setRowCount(0);
            progressModel.setRowCount(0);

            for (CaretakerShift schedule : system.getCaretakerShiftList().getScheduleDirectory()) {

                if (schedule.getStatus().equals("Pending")) {

                    Object[] pendingRow = new Object[5];
                    pendingRow[0] = schedule.getScheduleId();
                    pendingRow[1] = schedule.getRoomNumber();
                    pendingRow[2] = schedule.getDate();
                    pendingRow[3] = schedule.getTime();
                    pendingRow[4] = schedule.getStatus();

                    pendingModel.addRow(pendingRow);

                } else {

                    if (schedule.getCustomer().getCustomerId().equals(user.getCustomerId())) {

                        Object[] progressRow = new Object[5];
                        progressRow[0] = schedule.getScheduleId();
                        progressRow[1] = schedule.getRoomNumber();
                        progressRow[2] = schedule.getDate();
                        progressRow[3] = schedule.getTime();
                        progressRow[4] = schedule.getStatus();

                        progressModel.addRow(progressRow);
                    }
                }
            }

        } catch (Exception e) {

        }
    }
}
