/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import Enterprise.Database.DB4OUtil;
import Enterprise.main.EcoSystem;
import javax.swing.JFrame;
import java.io.File;
import java.util.Collections;
import java.util.Vector;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;


/**
 *
 * @author vardhankaranam25
 */
public class MainFrame extends javax.swing.JFrame {

    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    //private SysAdminJFrame sysadminJFrame;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        File fileRoot = new File("/Users/vardhankaranam/Downloads/final-project-teamsha-main/VacationVista/Databank.db4o");

        DefaultMutableTreeNode root = new DefaultMutableTreeNode(fileRoot);
        
        System.out.println("root: " + root + " ");
        
        //addNodes(root,fileRoot);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(153, 51, 255));

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(140, 82, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(140, 82, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(140, 82, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SplitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(255, 204, 255));
        workArea.setForeground(new java.awt.Color(140, 82, 255));
        workArea.setPreferredSize(new java.awt.Dimension(800, 800));
        workArea.setLayout(null);
        workArea.add(jLabel1);
        jLabel1.setBounds(1693, 106, 753, 483);
        workArea.add(jLabel4);
        jLabel4.setBounds(1419, 0, 268, 538);

        jLabel3.setFont(new java.awt.Font("Baskerville", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(140, 82, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Welcome to VacationVista");
        workArea.add(jLabel3);
        jLabel3.setBounds(28, 258, 614, 63);

        SplitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        Register registerPanel = new Register(system);
        SplitPane.setRightComponent(registerPanel);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        LoginPanel loginPanel = new LoginPanel(system, SplitPane);
        SplitPane.setRightComponent(loginPanel);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(system);
        LoginPanel loginPanel = new LoginPanel(system, SplitPane);
        SplitPane.setRightComponent(loginPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

//    public void treeConfigure() {
//
//        File fileRoot = new File("C:\\Users\\Asus\\Resort_Management_System");
//
//        DefaultMutableTreeNode root = new DefaultMutableTreeNode(fileRoot);
//        DefaultTreeModel model = new DefaultTreeModel(root);
//
//        File[] subItems = fileRoot.listFiles();
//        for (File file : subItems) {
//            if (!file.isDirectory()) {
//                root.add(new DefaultMutableTreeNode(file));
//            } else {
//                
//            }
//        }
//
//        this.jTree1.setModel(model);
//    }
    
//    void addNodes(DefaultMutableTreeNode curTop, File dir) {
//        
//    String curPath = dir.getPath();
//    DefaultMutableTreeNode curDir = new DefaultMutableTreeNode(curPath);
//    if (curTop != null) { // should only be null at root
//      curTop.add(curDir);
//    }
//    Vector ol = new Vector();
//    String[] tmp = dir.list();
//    System.out.println("dir.list() : " + dir.list());
//    for (int i = 0; i < tmp.length; i++)
//      ol.addElement(tmp[i]);
//    Collections.sort(ol, String.CASE_INSENSITIVE_ORDER);
//    File f;
//    Vector files = new Vector();
//    // Make two passes, one for Dirs and one for Files. This is #1.
//    for (int i = 0; i < ol.size(); i++) {
//      String thisObject = (String) ol.elementAt(i);
//      String newPath;
//      if (curPath.equals("."))
//        newPath = thisObject;
//      else
//        newPath = curPath + File.separator + thisObject;
//      if ((f = new File(newPath)).isDirectory())
//        addNodes(curDir, f);
//      else
//        files.addElement(thisObject);
//    }
//    // Pass two: for files.
//    for (int fnum = 0; fnum < files.size(); fnum++)
//      curDir.add(new DefaultMutableTreeNode(files.elementAt(fnum)));
//    
//    DefaultTreeModel model = new DefaultTreeModel(curDir);
//    this.jTree1.setModel(model);
//  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
