/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.EnterpriseManager;

import Enterprise.main.EcoSystem;
import Enterprise.Customer.Customer;
import java.util.ArrayList;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author rishika
 */
public class CreateUserAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRolesPanel
     */
    EcoSystem system;

    public CreateUserAdminPanel(EcoSystem system) {
        initComponents();
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        createUserBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin logo.png"))); // NOI18N

        setBackground(new java.awt.Color(255, 222, 242));
        setLayout(null);
        add(txtAge);
        txtAge.setBounds(560, 660, 203, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(140, 82, 255));
        jLabel2.setText("User Name");
        add(jLabel2);
        jLabel2.setBounds(370, 420, 119, 17);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(140, 82, 255));
        jLabel14.setText("Email Address");
        add(jLabel14);
        jLabel14.setBounds(370, 700, 130, 17);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(140, 82, 255));
        jLabel3.setText("Last Name");
        add(jLabel3);
        jLabel3.setBounds(370, 370, 119, 17);
        add(txtEmailAddress);
        txtEmailAddress.setBounds(560, 700, 203, 23);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(140, 82, 255));
        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(370, 470, 119, 17);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(140, 82, 255));
        jLabel5.setText("Roletype");
        add(jLabel5);
        jLabel5.setBounds(370, 510, 119, 17);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 82, 255));
        jLabel1.setText("First Name");
        add(jLabel1);
        jLabel1.setBounds(370, 330, 162, 17);
        add(txtAddress);
        txtAddress.setBounds(560, 560, 203, 23);
        add(txtFName);
        txtFName.setBounds(560, 320, 203, 23);
        add(txtPhoneNumber);
        txtPhoneNumber.setBounds(560, 610, 203, 23);
        add(txtLName);
        txtLName.setBounds(560, 370, 203, 23);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(140, 82, 255));
        jLabel8.setText("Address");
        add(jLabel8);
        jLabel8.setBounds(370, 560, 162, 17);
        add(txtUserName);
        txtUserName.setBounds(560, 420, 203, 23);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(140, 82, 255));
        jLabel10.setText("Age");
        add(jLabel10);
        jLabel10.setBounds(370, 660, 162, 17);
        add(txtPassword);
        txtPassword.setBounds(560, 460, 203, 23);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(140, 82, 255));
        jLabel11.setText("Phone Number");
        add(jLabel11);
        jLabel11.setBounds(370, 610, 162, 17);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehicle Contractor", "Pool Incharge", "Gaming Incharge", "Janitor", "Food Manager", "Laundry Manager", "Shop Manager" }));
        add(cmbRole);
        cmbRole.setBounds(560, 510, 203, 23);

        createUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createUserBtn.setForeground(new java.awt.Color(140, 82, 255));
        createUserBtn.setText("Create New User");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });
        add(createUserBtn);
        createUserBtn.setBounds(490, 770, 170, 21);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(140, 82, 255));
        jLabel6.setText("Create User Role");
        add(jLabel6);
        jLabel6.setBounds(410, 250, 550, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        // TODO add your handling code here:

        try {
            Customer user = new Customer();

            UUID uuid = UUID.randomUUID();
            String randomUUIDString = uuid.toString();

            String firstName = txtFName.getText();
            String lastName = txtLName.getText();
            String userName = txtUserName.getText();
            String password = txtPassword.getText();
            String address = txtAddress.getText();
            String age = txtAge.getText();
            String phoneNumber = txtPhoneNumber.getText();
            String userId = randomUUIDString;
            String roleType = (String) cmbRole.getSelectedItem();
            String emailAddress = txtEmailAddress.getText();

            if (firstName.isEmpty() || lastName.isEmpty() || userName.isEmpty() || password.isEmpty()
                    || phoneNumber.isEmpty() || userId.isEmpty() || age.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter all details !");
                return;
            }

            if (validatePhoneNumber(phoneNumber) == null) {
                JOptionPane.showMessageDialog(this, "Please enter a valid phone number !");
                return;
            }

            if (validateEmailAddress(emailAddress) == null) {
                JOptionPane.showMessageDialog(this, "Please enter a valid email address !");
                return;
            }

            if (validateAge(age) == null) {
                JOptionPane.showMessageDialog(this, "Please enter a valid age!");
                return;
            }

            for (Customer p : system.getCustomerList().getCustomer()) {
                if (userName.equals(p.getCustomerName())) {
                    JOptionPane.showMessageDialog(this, "Username already in use!");
                    return;
                }
            }
            Integer a = validateAge(age);
            Long pn = validatePhoneNumber(phoneNumber);

            user.setFirstName(firstName);
            user.setLastName(lastName);
            user.setCustomerName(userName);
            user.setPassword(password);
            user.setRoleType(roleType);
            user.setAge(a);
            user.setPhoneNumber(pn);
            user.setAddress(address);
            user.setEmailId(emailAddress);
            user.setCustomerId(userId);

            ArrayList<Customer> users = system.getCustomerList().getCustomer();
            users.add(user);
            system.getCustomerList().setCustomer(users);

            JOptionPane.showMessageDialog(this, "User successfully created!");
            clearAllFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter valid values for adding an user");
        }
    }//GEN-LAST:event_createUserBtnActionPerformed

    private Integer validateAge(String age) {
        try {
            return Integer.parseInt(age);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }
    }

    private Long validatePhoneNumber(String phoneNumber) {
        try {

            String cellPhoneNumberRegex = "^\\d{10}$";

            Pattern cellPhoneNumberPattern = Pattern.compile(cellPhoneNumberRegex);
            Matcher cellPhoneNumberMatcher = cellPhoneNumberPattern.matcher(phoneNumber);

            if (cellPhoneNumberMatcher.matches()) {
                return Long.parseLong(phoneNumber);
            } else {
                //JOptionPane.showMessageDialog(this, "Invalid Phone Number!");
                return null;
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }

    }

    private void clearAllFields() {
        txtAge.setText("");
        txtFName.setText("");
        txtLName.setText("");
        txtPassword.setText("");
        txtPhoneNumber.setText("");
        txtAddress.setText("");
        txtUserName.setText("");
        txtEmailAddress.setText("");
    }

    private String validateEmailAddress(String emailAddress) {
        try {

            String emailAddressRegex = "^(.+)@(\\S+)$";

            Pattern emailPattern = Pattern.compile(emailAddressRegex);
            Matcher emailMatcher = emailPattern.matcher(txtEmailAddress.getText());

            if (emailMatcher.matches()) {
                return emailAddress;
            } else {
//                JOptionPane.showMessageDialog(this, "Invalid Email Address!");
                return null;
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
